### ISSUE TITLE
Feat: 사용자의 Group List 조회 API 구현

### ISSUE THREAD

**Issue by jin-ttao** [Team-Bloblow/Bloblow-Server#10]
#### 요구사항 / Flow
로그인 사용자가 MyPage 진입시 자신이 만든 그룹 목록을 확인할 수 있다. (`/groups/{userId}`)
> 사용자 로그인 발생 > `userId`로 서버에 요청 > 해당 `userId`로 `group` schema 조회 > response로 `group` 정보 전달

#### Task
- [x] validation 로직: string 유효성 검사
- [x] `userId`를 key로 `group` Collection query
- [x] query 결과 response
- [x] error 로직

참고
<img src="https://github.com/user-attachments/assets/189e458c-fd24-41be-9bd1-da1ddc12d72e" width="500" height="300">
